// swift-tools-version: 5.9
// Generated by scripts/vendor-tree-sitter.mjs. Test-only: builds Core/ on macOS
// against the grammar sources the app pods pin; run the script with --fetch first.
import PackageDescription

let package = Package(
  name: "YohakuCode",
  platforms: [.macOS(.v13)],
  dependencies: [
    .package(url: "https://github.com/ChimeHQ/SwiftTreeSitter", exact: "0.10.0"),
  ],
  targets: [
    .target(
      name: "TreeSitterTypeScript",
      path: ".grammars/TreeSitterTypeScript",
      sources: ["typescript/src/parser.c", "typescript/src/scanner.c"],
      publicHeadersPath: "bindings/swift/typescript",
      cSettings: [.headerSearchPath("typescript/src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterTSX",
      path: ".grammars/TreeSitterTSX",
      sources: ["tsx/src/parser.c", "tsx/src/scanner.c"],
      publicHeadersPath: "bindings/swift/tsx",
      cSettings: [.headerSearchPath("tsx/src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterJavaScript",
      path: ".grammars/TreeSitterJavaScript",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterBash",
      path: ".grammars/TreeSitterBash",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterJSON",
      path: ".grammars/TreeSitterJSON",
      sources: ["src/parser.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterSwift",
      path: ".grammars/TreeSitterSwift",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterCSS",
      path: ".grammars/TreeSitterCSS",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterYAML",
      path: ".grammars/TreeSitterYAML",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterHTML",
      path: ".grammars/TreeSitterHTML",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterPython",
      path: ".grammars/TreeSitterPython",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterDiff",
      path: ".grammars/TreeSitterDiff",
      sources: ["src/parser.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterXML",
      path: ".grammars/TreeSitterXML",
      sources: ["xml/src/parser.c", "xml/src/scanner.c"],
      publicHeadersPath: "bindings/swift/xml",
      cSettings: [.headerSearchPath("xml/src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterTOML",
      path: ".grammars/TreeSitterTOML",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterDockerfile",
      path: ".grammars/TreeSitterDockerfile",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterLua",
      path: ".grammars/TreeSitterLua",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterGo",
      path: ".grammars/TreeSitterGo",
      sources: ["src/parser.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterJava",
      path: ".grammars/TreeSitterJava",
      sources: ["src/parser.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterC",
      path: ".grammars/TreeSitterC",
      sources: ["src/parser.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterMarkdown",
      path: ".grammars/TreeSitterMarkdown",
      sources: ["tree-sitter-markdown/src/parser.c", "tree-sitter-markdown/src/scanner.c"],
      publicHeadersPath: "tree-sitter-markdown/bindings/swift",
      cSettings: [.headerSearchPath("tree-sitter-markdown/src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterMarkdownInline",
      path: ".grammars/TreeSitterMarkdownInline",
      sources: ["tree-sitter-markdown-inline/src/parser.c", "tree-sitter-markdown-inline/src/scanner.c"],
      publicHeadersPath: "tree-sitter-markdown-inline/bindings/swift",
      cSettings: [.headerSearchPath("tree-sitter-markdown-inline/src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterRust",
      path: ".grammars/TreeSitterRust",
      sources: ["src/parser.c", "src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "TreeSitterPHP",
      path: ".grammars/TreeSitterPHP",
      sources: ["php/src/parser.c", "php/src/scanner.c"],
      publicHeadersPath: "bindings/swift",
      cSettings: [.headerSearchPath("php/src"), .unsafeFlags(["-w"])]
    ),
    .target(
      name: "YohakuCodeCore",
      dependencies: [
        .product(name: "SwiftTreeSitter", package: "SwiftTreeSitter"),
        .product(name: "SwiftTreeSitterLayer", package: "SwiftTreeSitter"),
        "TreeSitterTypeScript",
        "TreeSitterTSX",
        "TreeSitterJavaScript",
        "TreeSitterBash",
        "TreeSitterJSON",
        "TreeSitterSwift",
        "TreeSitterCSS",
        "TreeSitterYAML",
        "TreeSitterHTML",
        "TreeSitterPython",
        "TreeSitterDiff",
        "TreeSitterXML",
        "TreeSitterTOML",
        "TreeSitterDockerfile",
        "TreeSitterLua",
        "TreeSitterGo",
        "TreeSitterJava",
        "TreeSitterC",
        "TreeSitterMarkdown",
        "TreeSitterMarkdownInline",
        "TreeSitterRust",
        "TreeSitterPHP",
      ],
      path: "Core",
      resources: [.process("Queries")]
    ),
    .testTarget(name: "YohakuCodeCoreTests", dependencies: ["YohakuCodeCore"], path: "Tests"),
  ]
)
